#!/bin/bash

# Function to display information about a subdomain
display_info() {
    sub_domain=$1
    domain=$2
    
    # Perform DNS lookup and extract relevant information
    result=$(dig $sub_domain.$domain | awk '/ANSWER SECTION/ {getline; print $5}')
    
    # Display the information
    echo "The subdomain $sub_domain is a A record and points to $result"
}

# Main script starts here
if [ $# -eq 1 ]; then
    # If only domain name is provided, display information for default subdomains
    display_info www $1
    display_info lb-01 $1
    display_info web-01 $1
    display_info web-02 $1
elif [ $# -eq 2 ]; then
    # If both domain name and subdomain are provided, display information for the specified subdomain
    display_info $2 $1
else
    # Incorrect number of arguments provided
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi
