#!/usr/bin/env bash
# Installs nginx server

# Ensure script runs with sudo
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 
    exit 1
fi

# Update package lists
apt-get update

# Install nginx
apt-get install -y nginx

# Allow Nginx HTTP traffic
ufw allow 'Nginx HTTP'

# Create index.html with "Hello World!" message
echo "Hello World!" > /var/www/html/index.html

# Start nginx service
service nginx start
