#!/usr/bin/env bash
# This script displays the username, group ID, and shell full path from /etc/passwd

while IFS=: read -r username groupid shell; do
    echo "$username:$groupid:$shell"
done < /etc/passwd
