#!/usr/bin/env bash
# Bash script that creates an RSA key pair named school, Number of bits is 4096,
# tand he created key is protected by the passphrase betty
ssh-keygen -t rsa -b 4096 -f school -p "betty"
